### ISSUE TITLE
Disappearing UIView at poptorootview

### ISSUE THREAD

**Issue by gaborcsontos** [omaralbeik/InteractiveNavigationController#1]
Hi.

I tried to used the transition, but when I would like to go to the rootview it disappearing.

**Comment by omaralbeik** [comment]
Hey @gaborcsontos, sorry this project is outdated, I'll let you know when I have time to look at it :)

**Comment by gaborcsontos** [comment]
Any progress so far mate? :)

**Comment by gaborcsontos** [comment]
@omaralbeik ?

**Comment by omaralbeik** [comment]
Sorry @gaborcsontos Haven't got the time to investigate this, however, the code is a little bit outdated and need a complete re-write, you might want to use [`UIPageViewController`](https://developer.apple.com/documentation/uikit/uipageviewcontroller) to achieve a similar result. 

Here is an example project:
[Pages.zip](https://github.com/omaralbeik/InteractiveNavigationController/files/2020609/Pages.zip)

I'll deprecate this project due to the lack of time, thanks for understanding 😅

**Comment by gaborcsontos** [comment]
Unfortunatelly your solution were the perfect fit for my imagination.
